frontend_1  | [2021-09-20 15:19:43 +0000] [10] [ERROR] Exception in worker process
frontend_1  | Traceback (most recent call last):
frontend_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
frontend_1  |     worker.init_process()
frontend_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/gthread.py", line 92, in init_process
frontend_1  |     super().init_process()
frontend_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 134, in init_process
frontend_1  |     self.load_wsgi()
frontend_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
frontend_1  |     self.wsgi = self.app.wsgi()
frontend_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
frontend_1  |     self.callable = self.load()
frontend_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
frontend_1  |     return self.load_wsgiapp()
frontend_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
frontend_1  |     return util.import_app(self.app_uri)
frontend_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/util.py", line 359, in import_app
frontend_1  |     mod = importlib.import_module(module)
frontend_1  |   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
frontend_1  |     return _bootstrap._gcd_import(name[level:], package, level)
frontend_1  |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
frontend_1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
frontend_1  |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
frontend_1  |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
frontend_1  |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
frontend_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
frontend_1  |   File "/usr/src/app/webtool/__init__.py", line 16, in <module>
frontend_1  |     db = Database(logger=log, dbname=database_name, appname="frontend")
frontend_1  |   File "/usr/src/app/common/lib/database.py", line 54, in __init__
frontend_1  |     self.connection = psycopg2.connect(dbname=dbname, user=user, password=password, host=host, port=port, application_name=self.appname)
frontend_1  |   File "/usr/local/lib/python3.7/dist-packages/psycopg2/__init__.py", line 127, in connect
frontend_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
frontend_1  | psycopg2.OperationalError: could not connect to server: Connection refused
frontend_1  |   Is the server running on host "localhost" (127.0.0.1) and accepting
frontend_1  |   TCP/IP connections on port 5432?
frontend_1  | could not connect to server: Cannot assign requested address
frontend_1  |   Is the server running on host "localhost" (::1) and accepting
frontend_1  |   TCP/IP connections on port 5432?
frontend_1  |
frontend_1  | [2021-09-20 15:19:43 +0000] [10] [INFO] Worker exiting (pid: 10)
frontend_1  | [2021-09-20 15:19:43 +0000] [11] [ERROR] Exception in worker process
frontend_1  | Traceback (most recent call last):
frontend_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
frontend_1  |     worker.init_process()
frontend_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/gthread.py", line 92, in init_process
frontend_1  |     super().init_process()
frontend_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 134, in init_process
frontend_1  |     self.load_wsgi()
frontend_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
frontend_1  |     self.wsgi = self.app.wsgi()
frontend_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
frontend_1  |     self.callable = self.load()
frontend_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
frontend_1  |     return self.load_wsgiapp()
frontend_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
frontend_1  |     return util.import_app(self.app_uri)
frontend_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/util.py", line 359, in import_app
frontend_1  |     mod = importlib.import_module(module)
frontend_1  |   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
frontend_1  |     return _bootstrap._gcd_import(name[level:], package, level)
frontend_1  |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
frontend_1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
frontend_1  |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
frontend_1  |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
frontend_1  |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
frontend_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
frontend_1  |   File "/usr/src/app/webtool/__init__.py", line 16, in <module>
frontend_1  |     db = Database(logger=log, dbname=database_name, appname="frontend")
frontend_1  |   File "/usr/src/app/common/lib/database.py", line 54, in __init__
frontend_1  |     self.connection = psycopg2.connect(dbname=dbname, user=user, password=password, host=host, port=port, application_name=self.appname)
frontend_1  |   File "/usr/local/lib/python3.7/dist-packages/psycopg2/__init__.py", line 127, in connect
frontend_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
frontend_1  | psycopg2.OperationalError: could not connect to server: Connection refused
frontend_1  |   Is the server running on host "localhost" (127.0.0.1) and accepting
frontend_1  |   TCP/IP connections on port 5432?
frontend_1  | could not connect to server: Cannot assign requested address
frontend_1  |   Is the server running on host "localhost" (::1) and accepting
frontend_1  |   TCP/IP connections on port 5432?
frontend_1  |
frontend_1  | [2021-09-20 15:19:43 +0000] [11] [INFO] Worker exiting (pid: 11)
frontend_1  | [2021-09-20 15:19:43 +0000] [1] [WARNING] Worker with pid 11 was terminated due to signal 15
frontend_1  | [2021-09-20 15:19:43 +0000] [1] [INFO] Shutting down: Master
frontend_1  | [2021-09-20 15:19:43 +0000] [1] [INFO] Reason: Worker failed to boot.
4cat_frontend exited with code 3
